[package]
name = "rocket-opencv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
opencv = "0.62.0"
rocket = "0.5.0-rc.1"
